FROM alpine:latest

RUN apk update && apk add --no-cache x264-libs ffmpeg font-dejavu
RUN apk add --no-cache ca-certificates && update-ca-certificates
RUN fc-cache -f

WORKDIR /dash

COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
